- name: Clear YUM cache
  command: yum clean all

- name: Install dependencies
  yum:
    name:
      - yum-utils
      - ca-certificates
      - curl
      - socat
    state: present
    update_cache: yes

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

- name: FirewallD rules
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{item.port}}/{{item.proto}}"
    state: "{{item.state}}"
    zone: "{{item.zone}}"
  with_items:
   - {port: "6443", proto: "tcp", state: "enabled", zone: "public" }
   - {port: "2379-2380", proto: "tcp", state: "enabled", zone: "public" }
   - {port: "10250", proto: "tcp", state: "enabled", zone: "public" }
   - {port: "10259", proto: "tcp", state: "enabled", zone: "public" }
   - {port: "10257", proto: "tcp", state: "enabled", zone: "public" }
   - {port: "30000-32767", proto: "tcp", state: "enabled", zone: "public" }

- name: Reload firewalld to apply changes
  command: firewall-cmd --reload

- name: Load overlay module
  ansible.builtin.shell: modprobe overlay
  become: true
  ignore_errors: true

- name: Load br_netfilter module
  ansible.builtin.shell: modprobe br_netfilter
  become: true
  ignore_errors: true

- name: Ensure overlay and br_netfilter modules are loaded on boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s-modules.conf
    content: |
      overlay
      br_netfilter
  become: true

- name: Apply sysctl settings for Kubernetes
  ansible.builtin.sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Disable swap
  command: swapoff -a
  become: true

- name: Remove swap entry from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^/swap'
    state: absent

- name: Add Docker repository
  yum_repository:
    name: docker-ce
    description: Docker Community Edition
    baseurl: https://download.docker.com/linux/centos/9/x86_64/stable/
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: Install containerd
  yum:
    name: containerd.io
    state: present
    update_cache: yes

# - name: Configure containerd to enable CRI plugin
#   lineinfile:
#     path: /etc/containerd/config.toml
#     regexp: '^disabled_plugins'
#     line: '#disabled_plugins = []'
#   notify: Restart containerd

- name: get config.toml
  command: containerd config default > /etc/containerd/config.toml

- name: Set SystemdCgroup to true in containerd config
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^SystemdCgroup = false'
    line: 'SystemdCgroup = true'
    state: present

  notify: Restart containerd
- name: Ensure containerd service is started
  systemd:
    name: containerd
    enabled: yes
    state: started

