---
- name: Clear YUM cache
  command: yum clean all

- name: Install dependencies
  yum:
    name:
      - yum-utils
      - ca-certificates
      - curl
      - socat  # Install socat if needed
    state: present
    update_cache: yes

- name: Add containerd YUM repository
  yum_repository:
    name: containerd
    description: Containerd Repository
    baseurl: https://download.docker.com/linux/static/stable/x86_64/
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: Install containerd
  yum:
    name: containerd.io
    state: present
    update_cache: yes

- name: Enable and start containerd service
  systemd:
    name: containerd
    enabled: yes
    state: started

- name: Enable IP forwarding
  command: sysctl -w net.ipv4.ip_forward=1
  register: ip_forward
  changed_when: ip_forward.rc == 0

- name: Make IP forwarding persistent
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward = 1"
    state: present

- name: Reload sysctl settings
  command: sysctl -p

- name: Open required firewall ports
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - kubernetes
    - "6443/tcp"
    - "10250/tcp"
  when: ansible_facts['firewalld']['active'] | bool

- name: Add Kubernetes YUM repository
  yum_repository:
    name: kubernetes
    description: Kubernetes repository
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key

- name: Install Kubernetes packages
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Enable and start kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Disable swap (required for Kubernetes)
  command: swapoff -a
  when: ansible_virtualization_role == "guest"

- name: Initialize Kubernetes cluster on master
  command: kubeadm init
  when: inventory_hostname == "kubemaster"

- name: Set up kubeconfig for vagrant user
  become: true
  shell: |
    mkdir -p /home/vagrant/.kube
    cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    chown vagrant:vagrant /home/vagrant/.kube/config
  when: inventory_hostname == "kubemaster"
