---
- name: Clear YUM cache
  command: yum clean all

- name: Install dependencies
  yum:
    name:
      - yum-utils
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Add Kubernetes YUM repository
  yum_repository:
    name: kubernetes
    description: Kubernetes repository
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key

- name: Install Kubernetes packages
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Enable and start kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Disable swap (required for Kubernetes)
  command: swapoff -a
  when: ansible_virtualization_role == "guest"

- name: Initialize Kubernetes cluster on master
  command: kubeadm init
  when: inventory_hostname == "kubemaster"

- name: Set up kubeconfig for vagrant user
  become: true
  shell: |
    mkdir -p /home/vagrant/.kube
    cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    chown vagrant:vagrant /home/vagrant/.kube/config
  when: inventory_hostname == "kubemaster"
