all:
  hosts:
    kubemaster:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_connection: local
    kubenode01:
      ansible_host: 192.168.33.11
      ansible_user: vagrant
    kubenode02:
      ansible_host: 192.168.33.12
      ansible_user: vagrant
