all:
  hosts:
    kubemaster:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_connection: local
    kubenode1:
      ansible_host: kubenode1
      ansible_user: vagrant
    kubenode2:
      ansible_host: kubenode2
      ansible_user: vagrant
