all:
  children:
    master:
      hosts:
        kubemaster:
          ansible_host: 127.0.0.1
          ansible_connection: local
    workers:
      hosts:
        kubenode01:
          ansible_host: 10.100.0.11
        kubenode02:
          ansible_host: 10.100.0.12