all:
  hosts:
    kubemaster:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_connection: local
    kubenode1:
      ansible_host: 192.168.50.11
      ansible_user: vagrant
    kubenode2:
      ansible_host: 192.168.50.12
      ansible_user: vagrant
